logging:
  level:
    root: info
    com.czetsuyatech: debug
    org.springframework: info
    org.hibernate.SQL: info
    org.hibernate.type.descriptor.sql.BasicBinder: error

spring:
  # Datasource Configuration
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3301/unifiedevents
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: db_user
    password: db_pass_123
    hikari:
      connection-test-query: SELECT 1
      jdbc-url: ${spring.datasource.url}
      maximum-pool-size: 17
      minimum-idle: 10
      pool-name: ue-db-pool
      username: ${spring.datasource.username}
      password: ${spring.datasource.password}

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 5
        generate_statistics: false
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migrations
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

app:
  name: UnifiedKafkaEvents

unified-kafka-events:
  enabled: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer-group: Lab
    retry-delay: 60
    max-retry-attempts: 5
    properties:
      version: 1
    inbound:
      retry-cron: 0 0/2 * ? * *
      retry-chunk-size: 100
      clean-cron: 0 0 0 ? 1/3 *
      clean-lifespan: 30
      topics:
        ok-events:
          name: Unified.Kafka.Events.ok
          consumer-instance: 1
        ko-events:
          name: Unified.Kafka.Events.ko
          consumer-instance: 1
        ko-events-retry:
          name: Unified.Kafka.Events.ko-retry
          consumer-instance: 1
        ignored-events:
          name: Unified.Kafka.Events.ignored
          consumer-instance: 1
    outbound:
      retry-cron: 0 0/2 * ? * *
      retry-chunk-size: 100
      clean-cron: 0 0 0 ? 1/3 *
      clean-lifespan: 30
      topics:
        ok-events:
          name: Unified.Kafka.Events.ok
        ko-events:
          name: Unified.Kafka.Events.ko
        ignored-events:
          name: Unified.Kafka.Events.ignored
