version: '3.8'

networks:
  backend:

services:
  unified-kafka-events-db:
    image: mysql:8.0.31
    container_name: db-unified-events
    ports:
      - 3301:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: unifiedevents
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass_123
    command: mysqld --sql_mode="NO_ENGINE_SUBSTITUTION"
    networks:
      - backend

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.8
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.0.8
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  kafdrop:
    image: obsidiandynamics/kafdrop
    hostname: kafdrop
    container_name: kafdrop
    depends_on:
      - broker
    ports:
      - "9090:9000"
    environment:
      KAFKA_BROKERCONNECT: broker:29092
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
